name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        uses: koyeb-community/install-koyeb-cli@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}

      - name: Redeploy Koyeb Service
        run: koyeb service redeploy slow-fredia/modul-1-coding-standards